apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-httpd-app
  labels:
    app: httpd
spec:
  replicas: 3  # Number of replicas (pods) to run
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: my-httpd-container
          image: your-registry/your-httpd-image:latest  # Replace with your actual image URL
          ports:
            - containerPort: 80

