apiVersion: v1
kind: Service
metadata:
  name: my-httpd-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes the service using a cloud provider's load balancer (requires a cloud provider)

